# This flag tells the Android Gradle Plugin that your project uses AndroidX libraries.
android.useAndroidX=true

# This flag tells the Android Gradle Plugin to automatically migrate any third-party 
# libraries that might still be using the old support library names to AndroidX.
# It's a best practice to enable it alongside useAndroidX.
android.enableJetifier=true
